<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SUB>
<SUB AME_VERSION="2604" DOC_VERSION="6" HOTFIX="0" MAJ="20261" UPDATE="0">
 <Supercomponent catname="nw2" scSubName="SC_123">
  <PortsMap>
   <Map>
    <PortMap component="0" face="3" labelX="0.000000" labelY="0.000000" port="0" type="signal" x="107" y="82" />
   </Map>
  </PortsMap>
  <Circuit ameApplication="AMESim" highestId="9">
   <Comps>
    <Comp alias="constant" circuitScopeId="1" depth="201" displayName="constant" geometry="1" iconDescription="constant signal source" labelVisible="0" libraryId="sig.constant" name="constant" scaleX="1.000000" scaleY="1.000000" type="0">
     <Pos x="67" y="67" />
     <LabelPos configured="0" direction="0" x="0" y="0" />
     <CirCompIcon cirIconIdentity="1" cirPortGraphics="IDxQT1JUUz4KICA8UE9SVCBmYWNlPSIzIiB0eXBlPSJzaWduYWwiIHg9IjQwIiB5PSIxNSI+CiAgIDxQT1JUX0JJVE1BUD4kQU1FL2xpYnBvcnRzL0ljb25zL3NpZ25hbDFweC5zdmc8L1BPUlRfQklUTUFQPgogIDwvUE9SVD4KIDwvUE9SVFM+Cg==" cirPortHidden="0">
      <IconMap data="H4sIAAAAAAACCo1SsY7bMAzd8xUEb3ALXGTLzqF2EOVwHTp16NDOgevIDhFZMiSd7fTrKzlOu3SoIIDUE/XIR/HwOvcKRmkdGS0SzrIEpG7MmXQnkh/fv2zL5PW4ObixgxCp3b7upaNe4KjPTPWOUV93pCW743iPEnjxftin6TRNbCqYsV2aZ1mWBp41ZD8r0td/BfKqqtLlFv9UhpzlCD9rJ79Z05KSAj3pGwKdBX6lUSplTjxQC8yGGeG22onO/iJwtxwukrqLF5hX8TSSnD6b+AAy2GWQVwgm5GuVmQS6xhqlllr3bqibkHCw0kk7Sgz96I4bADg0ZBslIRSkBD61y0Jw3pprePCULesBbHvy0ioKJugJcBOS8x17Cd7t4dnoYHqn93L24G2tXWts6Hlfe0vzBw6xZA487JLlxY5/RGiN9tu27kkFruTNUq2SFXX0S0baoPp4PaSRNUhIu6hjaWDz7vyJnxx1ulZ4zx36/xCmjZb/r2rmAosifAF/aJrz+AMByVdklTcYdeuMhsGQ9mFm8vKZc/YCRc74cwyEiHxabclKKApW/b3JWA4Qye5a4nAdN78BjYBj0dICAAA=" format="svgz/base64" />
     </CirCompIcon>
     <Ports>
      <Port connect="0" decorationOrientation="0" decorationVisible="0" face="3" name="" type="signal">
       <Pos x="40" y="15" />
       <DecorationBoundingRect height="0" width="0" x="0" y="0" />
       <Connects>
        <Connect num="-1" port="0" />
       </Connects>
      </Port>
     </Ports>
     <Submodel autonomousCompilation="False" autonomousRuntime="False" cirPortsOverFramework="0" codeGenVersion="2.0" dir="$AME/libsig/submodels" discontinuity="1" hasTerminate="1" idMax="29" idsReset="0" label="constant signal" name="CONS00" outputType="1" type="0" unit="1">
      <RealParams>
       <Params>
        <Param defValue="1" historyVariable="k0GEN" maxValue="1e+30" minValue="-1e+30" subId="3" title="constant value" tunable="True" units="null" value="1" varName="k" visibility="True" />
       </Params>
      </RealParams>
      <ParamsGroups>
       <Group circuitScopeId="4" editable="0" editableTitle="1" groupHeadIcon="" name="ROOTGROUP" origTitle="ROOTGROUP" subId="29">
        <Elements>
         <Element display="0" varName="k" />
         <Element display="1" varName="out" />
        </Elements>
       </Group>
      </ParamsGroups>
      <IntVars>
       <Vars>
        <Var defValue="0" dimension="1" maxValue="1e+30" minValue="-1e+30" saveValue="1" subId="28" title="constant value - Linked variable" type="10" units="null" value="0" varName="k0GEN" visibility="False">
         <LaData>
          <Data laStatus="0" />
         </LaData>
        </Var>
       </Vars>
      </IntVars>
      <ExtVars>
       <Port tag="signal">
        <Vars>
         <Var dimension="1" io="2" saveValue="1" subId="24" title="output" type="0" units="null" varName="out" visibility="True">
          <LaData>
           <Data laStatus="0" />
          </LaData>
         </Var>
        </Vars>
       </Port>
      </ExtVars>
     </Submodel>
    </Comp>
   </Comps>
   <animationProperties loop="0" speed="1" />
   <globalParams />
  </Circuit>
 </Supercomponent>
</SUB>
